services:
  nginx:
    image: nginx:1.27.0
    container_name: nginx-review
    volumes:
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www/review-system
    ports:
      - "80:80"
    depends_on:
      - php-fpm

  php-fpm:
    build:
      context: .
      dockerfile: docker/php-fpm.Dockerfile
    container_name: php-fpm-review
    volumes:
      - ./:/var/www/review-system
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini:ro
      - ./docker/php/hosts:/etc/hosts
    depends_on:
      - postgres

  php-cli:
    build:
      context: .
      dockerfile: docker/php-cli.Dockerfile
    container_name: php-cli-review
    volumes:
      - ~/.ssh:/home/www-data/.ssh
      - ~/.bash_history:/home/www-data/.bash_history
      - ./:/var/www/review-system
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini:ro
      - ./docker/php/hosts:/etc/hosts
    tty: true
    depends_on:
      - postgres

  postgres:
    image: postgres:16.5
    container_name: postgres-review
    environment:
      POSTGRES_DB: review_system
      POSTGRES_USER: 'admin'
      POSTGRES_PASSWORD: admin
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: